apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: hello
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: hello
spec:
  commonName: helloworldsdemo.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
